#!/usr/bin/env bash

type watchman >/dev/null 2>&1 || { echo >&2 "Please install watchman: https://facebook.github.io/watchman/docs/install/"; exit 1; }
type hotserve >/dev/null 2>&1 || { echo >&2 "Please install hotserve: npm i -g hotserve"; exit 2; }

hotserve "" 1100 '*'
